### ISSUE TITLE
integrate golangci-lint

### ISSUE THREAD

**Issue by noornee** [serene-brew/Kaizen#11]
we should integrate `golangci-lint` into this project to automate code quality checks and enforce consistent coding standards.

I’ve noticed that some variable names use both camelCase and snake_case, but in Go, the standard convention is to use camelCase for variable names.

**Comment by ImonChakraborty** [comment]
Hey, @noornee !!

Great idea to automate code quality checks, can you handle this one, please??

**Comment by noornee** [comment]
> Hey, @noornee !!
> 
> Great idea to automate code quality checks, can you handle this one, please??

hii @ImonChakraborty 
yes i can. i'll start working on this now

**Comment by ImonChakraborty** [comment]
> > Hey, @noornee !!
> > Great idea to automate code quality checks, can you handle this one, please??
> 
> hii @ImonChakraborty yes i can. i'll start working on this now

Great!!!

Thanks for your help

**Comment by mintRaven-05** [comment]
the lint works as expected!! ...

as usual, GREAT WORK @noornee 
thanks !!
