### ISSUE TITLE
repo size is too large. (over 50MB)

### ISSUE THREAD

**Issue by noornee** [serene-brew/Kaizen#3]
### misc
Hello, i came across Kaizen from a reddit post and i love what you guys have accomplished with this project.
I've always wanted to navigate anime sites directly from the terminal. a few years ago ,i worked on a dead simple cli tool to scrape anime download links from a specific website but the site went offline and i didnt maintain the repo after that.

im really excited to see a project like this come to life-- thank you for building this!!

## issue
i noticed that the `assets` directory is > 50MB and which is quite large. i wanna suggest uploading the videos directly to github as file attachments. here's a reference from the github doc
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

thanks again!

**Comment by mintRaven-05** [comment]
## Thanks @noornee for your feedback. This really boosts our morale to continue building this. 

## About the issue
you are absolutely right, lemme fix it and once again thanks. Feel free to share any ideas in you mind in the discussions page.

**Comment by noornee** [comment]
you're welcome @mintRaven-05 ^^

i noticed that the repos is still large. this is because the files are still present in the github history. i remember i once used a tool to remove large files from a git history but i cant really remember what i used anymore :/

**Comment by mintRaven-05** [comment]
I was able to reduce it down to 19mb. i was trying out git filter-repo, but it was not working for some reason. So I tried BFG and it seems like it was able to delete it from the github history. Can you please verify it once ?
If the size is still an issue, consider trying out the latest release v1.0.2
the source code zip has a total of 6.5 mb

**Comment by noornee** [comment]
> I was able to reduce it down to 19mb. i was trying out git filter-repo, but it was not working for some reason. So I tried BFG and it seems like it was able to delete it from the github history. Can you please verify it once ?

niceee. i did and the size was approx 31MB. 
since the assets has been purged from the history, i think the only thing left is to 
- delete the binary
- purge it from the history (using BFG)
- use a github action to build the binaries for diff arch. [goreleaser](https://goreleaser.com/ci/actions/)
- modify  `install.sh` to download the binary from the release page based on the arch of the system where the script is executed

> If the size is still an issue, consider trying out the latest release v1.0.2
> the source code zip has a total of 6.5 mb

the size is not really an issue for me. i just feel its way better if the size of the repo isnt large-

**Comment by mintRaven-05** [comment]
hey @noornee, i was able to reduce the significantly

**Comment by noornee** [comment]
> ### hey @noornee, i was able to reduce the size significantly. I forgot few things earlier to do lol
> > * delete the binary
> > * purge it from the history (using BFG)
> 
> I purged the build directory and removed it from the history. Previously i forgot to add some tags in BFG and it was not able to remove the `assets` directory completely from the reflogs, hence it was still pointing to those histories and hence the size difference (for me: 19mb and for you: 31mb) . But this time along with the `build` directory, i removed the `assets` from the history too.

ahh i see. Thanks!

> 
> > * use a github action to build the binaries for diff arch. [goreleaser](https://goreleaser.com/ci/actions/)
> > * modify install.sh to download the binary from the release page based on the arch of the system where the script is executed
> 
> About this, can you please do me favour and contribute this to our project. Because i don't quite understand what or how is this working. We will be more than glad, if you participate in this since we value your participation in this

Definitely!
I'd love to contribute to this project to help resolve this. I would make a pull request soon

**Comment by mintRaven-05** [comment]
GREAT !!
We will be waiting for the PR, 
thank you so much for your help

**Comment by mintRaven-05** [comment]
Lol, no problem.
I was wondering the same thing, cuz we were building the binary using Makefile. But I was not aware about goreleaser.
thanks for setting it up.
Hope you are enjoying `Kaizen`

**Comment by noornee** [comment]
> Lol, no problem. 

Thanks :D

> I was wondering the same thing, cuz we were building the binary using Makefile.

righttt? cant believe i missed that!

> But I was not aware about goreleaser. thanks for setting it up. Hope you are enjoying `Kaizen`

You're welcome and thanks to you too!

yupp, im enjoying Kaizen. i used it to stream an episode of bleach yesterday. i intend to use it properly today ^^
