### ISSUE TITLE
[BUG]: The Episode availability is not accurate

### ISSUE THREAD

**Issue by ImonChakraborty** [serene-brew/Kaizen#6]
This is a known issue and we are working on it, Kaizen will be down for some time till this issue gets fixed.

The Backend and API logic and integration needs to be changed in the mean time.

Please have patience while we are working on it.

**Comment by mintRaven-05** [comment]
modifed API integration done !
AutoHeal feature implemented and no new bugs (fixed previous bugs)
am closing this issue with the modified version `v1.1.2`
