### ISSUE TITLE
[GORELEASER]: remove windows binaries and create 32 bit binaries for linux and darwin architectures

### ISSUE THREAD

**Issue by mintRaven-05** [serene-brew/Kaizen#7]
hey @noornee, can you please modify the goreleaser workflow. I dont want to create windows binaries since its not compatible on windows yet. I just wanna keep the linux and darwin binaries (but include 32 bit binaries as well please)

## misc
I am sorry if you are facing some difficulty with kaizen. We are working on a bug and trying to resolve it ASAP. We are also working on some extra features like Auto Heal and install missing internal dependencies automatically and show warnings for missing external dependencies.

it will be of great help if you modify the goreleaser workflow. Be sure to sync your repo with mine before sending a PR

**Comment by noornee** [comment]
> hey @noornee, can you please modify the goreleaser workflow. I dont want to create windows binaries since its not compatible on windows yet. I just wanna keep the linux and darwin binaries (but include 32 bit binaries as well please)

Hii @mintRaven-05  alright, i'll look into it and open a PR

> I am sorry if you are facing some difficulty with kaizen. We are working on a bug and trying to resolve it ASAP. We are also working on some extra features like Auto Heal and install missing internal dependencies automatically and show warnings for missing external dependencies.

ahh, alright. good luck!

> it will be of great help if you modify the goreleaser workflow. Be sure to sync your repo with mine before sending a PR

sureee
