### ISSUE TITLE
MPV Installation Check Fails on Non-FHS Compliant Systems

### ISSUE THREAD

**Issue by noornee** [serene-brew/Kaizen#9]
The current logic used to check for the installation of MPV relies on a fixed path `/usr/bin/mpv`, which is not compliant with all linux operating systems that do not follow the Filesystem Hierarchy Standard (FHS).

i use nixos btw and this failes.

https://github.com/serene-brew/Kaizen/blob/458d67e526f9e817c26ce599b0fd09f041d08afb/main.go#L16

**Comment by noornee** [comment]
also, i wanna suggest moving these custom files 
- uninstall.sh
- update.sh
- VERSION

from `~/.local` to `~/.local/share` 

so `~/.local/share/kaizen`

**Comment by mintRaven-05** [comment]
>also, i wanna suggest moving these custom files
>
>   * uninstall.sh
>   * update.sh
>   * VERSION
>
>from `~/.local` to `~/.local/share`
>
>so `~/.local/share/kaizen`

ask and ye shall receive, am changing that

>The current logic used to check for the installation of MPV relies on a fixed path /usr/bin/mpv, which is not compliant with > all linux operating systems that do not follow the Filesystem Hierarchy Standard (FHS).
>
> i use nixos btw and this failes.
about this, i can remove it for now untill i find a solution, will that work ?

**Comment by noornee** [comment]
> > also, i wanna suggest moving these custom files
> > 
> > * uninstall.sh
> > * update.sh
> > * VERSION
> > 
> > from `~/.local` to `~/.local/share`
> > so `~/.local/share/kaizen`
> 
> ask and ye shall receive, am changing that

:joy:  thanks!
> 
> > The current logic used to check for the installation of MPV relies on a fixed path /usr/bin/mpv, which is not compliant with > all linux operating systems that do not follow the Filesystem Hierarchy Standard (FHS).
> > i use nixos btw and this failes.
> 
> about this, i can remove it for now untill i find a solution, will that work ?

check this https://pkg.go.dev/os/exec#LookPath
i tested it on my machine and it works

**Comment by mintRaven-05** [comment]
>check this https://pkg.go.dev/os/exec#LookPath
>i tested it on my machine and it works

okayyy!!, i can use this function
hey thanks for the solution

**Comment by mintRaven-05** [comment]
All set @noornee 
now here is what i wanna check
* run `kaizen -update` and verify whether the update was a success or not. use `kaizen -v` to check for the new version installed.
* verify whether files are now being stored in ~/.local./share/kaizen
* if the update fails, i want you to tell me that here and uninstall it completely and install it once again by cloning the updated repo.
* there are chances that the update script might fail becuase of the conflicting paths, however chances are low

**Comment by noornee** [comment]
@mintRaven-05 everything works perfectly. ^^
![image](https://github.com/user-attachments/assets/9e84b635-a016-41bf-9dae-da8d0d18e6a1)

**Comment by mintRaven-05** [comment]
perfect, is the app still able to search for anime ?
or is it dead ?

**Comment by noornee** [comment]
> perfect, is the app still able to search for anime ? or is it dead ?

yupp, i can stiil search and stream

**Comment by mintRaven-05** [comment]
niceee !!
hey thanks for you help today. So i guess i am closing this issue
